name: Build Release AAB for Play Store

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2

      - name: Decode Keystore from Secret
        run: |
          echo "${{ secrets.UPLOAD_KEYSTORE_BASE64 }}" | base64 --decode > app/upload-keystore.jks
          ls -lh app/upload-keystore.jks

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release Bundle with new keystore
        env:
          STORE_PASS: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.UPLOAD_KEY_ALIAS }}
          KEY_PASS: ${{ secrets.UPLOAD_KEY_PASSWORD }}
        run: |
          ./gradlew bundleRelease --stacktrace -Pandroid.injected.signing.store.file=app/upload-keystore.jks -Pandroid.injected.signing.store.password=$STORE_PASS -Pandroid.injected.signing.key.alias=$KEY_ALIAS -Pandroid.injected.signing.key.password=$KEY_PASS

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasl-release-aab-ready
          path: app/build/outputs/bundle/release/*.aab
          retention-days: 10
